In [1]:
import sys
sys.executable

'C:\\Users\\DELL\\Downloads\\ItineraireVacances\\.venv\\Scripts\\python.exe'

# Dataset — AirBnb Paris
(1,12 GB, 5 file, 108 columns, 703 downloads, Updated 7 years ago)

https://www.kaggle.com/datasets/juliatb/airbnb-paris?select=reviews.csv

In [2]:
import pandas as pd
import numpy as np
import pyarrow
import json
from IPython.display import display
import folium
from folium.plugins import MarkerCluster

# 1. Charger les données

### 1.1. Dataset "listings.csv"

In [3]:
#lire CSV_PATH
CSV_PATH = "listings.csv"
df_listings = pd.read_csv(CSV_PATH, sep=',', encoding='utf-8', low_memory = False)

#Convertir en Parquet --> Fichier beaucoup plus léger --> Lecture rapide
PARQUET_PATH = "listings.parquet"
df_listings.to_parquet(PARQUET_PATH, compression = "snappy")

#Libère la mémoire et recharger le parquet
del df_listings
df_listings = pd.read_parquet("listings.parquet")

#Afficher 2 lignes et TOUTES les colonnes
pd.set_option("display.max_columns", None)
display(df_listings.head(3))

print("\n-------------------------------------")
print("Nombre de lignes et de colones")
print(df_listings.shape)

print("\n-------------------------------------")
print("Display info sur les colonnes et datatype")
display(df_listings.info())

id                        listing_url       scrape_id last_scraped  \
0  2577  https://www.airbnb.com/rooms/2577  20181207151406   2018-12-08   
1  3109  https://www.airbnb.com/rooms/3109  20181207151406   2018-12-08   
2  5396  https://www.airbnb.com/rooms/5396  20181207151406   2018-12-08   

                               name  \
0  Loft for 4 by Canal Saint Martin   
1                      zen and calm   
2    Explore the heart of old Paris   

                                             summary  \
0  100 m2 loft (1100 sq feet) with high ceiling, ...   
1  Appartement très calme de 50M2 Belle lumière D...   
2  Cozy, well-appointed and graciously designed s...   

                                               space  \
0  The district has any service or shop you may d...   
1                   I bedroom appartment in Paris 14   
2  Small, well appointed studio apartment at the ...   

                                         description experiences_offered  \
0  100 m2 loft (1100 sq feet) with high ceiling, ...                none   
1                   I bedroom appartment in Paris 14                none   
2  Cozy, well-appointed and graciously designed s...                none   

                               neighborhood_overview  \
0                                               None   
1                                               None   
2  You are within walking distance to the Louvre,...   

                                               notes  \
0                                               None   
1                                               None   
2  The staircase leading up to the apartment is n...   

                                             transit  \
0                      Metro lines : 4, 8, 3, 11, 9.   
1                        ligne 13 and RER B, Ligne 4   
2  The flat is close to two or three major metro ...   

                                              access  \
0                                               None   
1                                               None   
2  The flat includes its own modern bathroom, a w...   

                                         interaction  \
0                                               None   
1                             yes I can help you out   
2  We expect guests to operate rather independent...   

                                         house_rules  thumbnail_url  \
0                                               None            NaN   
1                                               None            NaN   
2  This is a small flat in a very old building th...            NaN   

   medium_url                                        picture_url  \
0         NaN  https://a0.muscache.com/im/pictures/09da057c-0...   
1         NaN  https://a0.muscache.com/im/pictures/baeae9e2-c...   
2         NaN  https://a0.muscache.com/im/pictures/52413/f9bf...   

   xl_picture_url  host_id                                host_url host_name  \
0             NaN     2827  https://www.airbnb.com/users/show/2827    Karine   
1             NaN     3631  https://www.airbnb.com/users/show/3631      Anne   
2             NaN     7903  https://www.airbnb.com/users/show/7903    Borzou   

   host_since                          host_location  \
0  2008-09-09  Casablanca, Grand Casablanca, Morocco   
1  2008-10-14           Paris, Île-de-France, France   
2  2009-02-14             Istanbul, İstanbul, Turkey   

                                          host_about host_response_time  \
0  Arrivée à Casablanca il y a 4 ans, je suis amo...       within a day   
1                                               None       within a day   
2  We are both journalists based in the Middle Ea...     within an hour   

  host_response_rate  host_acceptance_rate host_is_superhost  \
0                75%                   NaN                 f   
1               100%                   NaN                 f   
2               100%                   NaN                 f   

     


-------------------------------------
Nombre de lignes et de colones
(59881, 96)

-------------------------------------
Display info sur les colonnes et datatype
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59881 entries, 0 to 59880
Data columns (total 96 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   id                                59881 non-null  int64  
 1   listing_url                       59881 non-null  object 
 2   scrape_id                         59881 non-null  int64  
 3   last_scraped                      59881 non-null  object 
 4   name                              59807 non-null  object 
 5   summary                           57524 non-null  object 
 6   space                             40516 non-null  object 
 7   description                       59384 non-null  object 
 8   experiences_offered               59881 non-null  object 
 9   neighborhood_overview         

None

### 1.2. Dataset "calendar.csv"

In [4]:
#lire CSV_PATH
CSV_PATH = "calendar.csv"
df_calendar = pd.read_csv(CSV_PATH, sep=',', encoding='utf-8', low_memory = False)

#Convertir en Parquet --> Fichier beaucoup plus léger --> Lecture rapide
PARQUET_PATH = "calendar.parquet"
df_calendar.to_parquet(PARQUET_PATH, compression = "snappy")

#Libère la mémoire et recharger le parquet
del df_calendar
df_calendar = pd.read_parquet("calendar.parquet")

#Afficher 2 lignes et TOUTES les colonnes
pd.set_option("display.max_columns", None)
display(df_calendar.head(3))

print("\n-------------------------------------")
print("Nombre de lignes et de colones")
print(df_calendar.shape)

print("\n-------------------------------------")
print("Display info sur les colonnes et datatype")
display(df_calendar.info())

listing_id        date available    price
0       79690  2019-12-07         t  $185.00
1       79690  2019-12-06         t  $185.00
2       79690  2019-12-05         t  $185.00


-------------------------------------
Nombre de lignes et de colones
(21856565, 4)

-------------------------------------
Display info sur les colonnes et datatype
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21856565 entries, 0 to 21856564
Data columns (total 4 columns):
 #   Column      Dtype 
---  ------      ----- 
 0   listing_id  int64 
 1   date        object
 2   available   object
 3   price       object
dtypes: int64(1), object(3)
memory usage: 667.0+ MB


None

### 1.3. Dataset "reviews.csv"

In [21]:
#lire CSV_PATH
CSV_PATH = "reviews.csv"
df_reviews = pd.read_csv(CSV_PATH, sep=',', encoding='utf-8', low_memory = False)

#Convertir en Parquet --> Fichier beaucoup plus léger --> Lecture rapide
PARQUET_PATH = "reviews.parquet"
df_reviews.to_parquet(PARQUET_PATH, compression = "snappy")

#Libère la mémoire et recharger le parquet
del df_reviews
df_reviews = pd.read_parquet("reviews.parquet")

#Afficher 2 lignes et TOUTES les colonnes
pd.set_option("display.max_columns", None)
display(df_reviews.head(5))

print("\n-------------------------------------")
print("Nombre de lignes et de colones")
print(df_reviews.shape)

print("\n-------------------------------------")
print("Display info sur les colonnes et datatype")
display(df_reviews.info())

listing_id         id        date  reviewer_id reviewer_name  \
0        3109  123127969  2016-12-27     12389804        Sophie   
1        3109  123274144  2016-12-28     67553494         Tom'S   
2        3109  207127433  2017-10-28     51636494      Patricia   
3        3109  208779822  2017-11-03      4142888      Patricia   
4        3109  234257457  2018-02-12      3539452     Dominique   

                                            comments  
0  The host canceled this reservation the day bef...  
1  The host canceled this reservation 2 days befo...  
2            Tout s'est bien déroulé. Merci bien. PG  
3  Un petit nid fouiller douillet situé dans  app...  
4  The host canceled this reservation 8 days befo...


-------------------------------------
Nombre de lignes et de colones
(1103367, 6)

-------------------------------------
Display info sur les colonnes et datatype
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1103367 entries, 0 to 1103366
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype 
---  ------         --------------    ----- 
 0   listing_id     1103367 non-null  int64 
 1   id             1103367 non-null  int64 
 2   date           1103367 non-null  object
 3   reviewer_id    1103367 non-null  int64 
 4   reviewer_name  1103366 non-null  object
 5   comments       1102133 non-null  object
dtypes: int64(3), object(3)
memory usage: 50.5+ MB


None

# 2. Décrire les colonnes essentielles du dataset "listings.csv"

### 2.1. Les colonnes Dtype float64

In [22]:
#Vérifier les valeurs manquantes des colonnes Dtype float64
print("\n-------------------------------------")
print("Les valeurs manquantes des colonnes Dtype float64 (sur 59881 lignes) :")
print("---------------------------------------")
missing_float64_summary = pd.DataFrame({"missing_count": df_listings.select_dtypes(include="float64").isna().sum(),
                                        "missing_pct": (df_listings.select_dtypes(include="float64").isna().sum() / 59881 * 100).round(2)}
                                      ).sort_values("missing_pct", ascending=False)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

display(missing_float64_summary)


-------------------------------------
Les valeurs manquantes des colonnes Dtype float64 (sur 59881 lignes) :
---------------------------------------


missing_count  missing_pct
thumbnail_url                         59881       100.00
medium_url                            59881       100.00
xl_picture_url                        59881       100.00
host_acceptance_rate                  59881       100.00
neighbourhood_group_cleansed          59881       100.00
square_feet                           58523        97.73
review_scores_value                   13689        22.86
review_scores_location                13688        22.86
review_scores_checkin                 13689        22.86
review_scores_accuracy                13657        22.81
review_scores_communication           13651        22.80
review_scores_cleanliness             13636        22.77
review_scores_rating                  13592        22.70
reviews_per_month                     12492        20.86
beds                                    228         0.38
bathrooms                                76         0.13
bedrooms                                 68         0.11
host_listings_count                       8         0.01
host_total_listings_count                 8         0.01
latitude                                  0         0.00
longitude                                 0         0.00

In [23]:
print("---------------------------------------")
print("Describe la colonne review_scores_value (23% missing):")
print("---------------------------------------")
display(df_listings["review_scores_value"].unique())
display(df_listings["review_scores_value"].describe())

print("\n-------------------------------------")
print("Describe la colonne review_scores_location (23% missing):")
print("---------------------------------------")
display(df_listings["review_scores_location"].unique())
display(df_listings["review_scores_location"].describe())

print("\n-------------------------------------")
print("Describe la colonne review_scores_checkin (23% missing):")
print("---------------------------------------")
display(df_listings["review_scores_checkin"].unique())
display(df_listings["review_scores_checkin"].describe())

print("\n-------------------------------------")
print("Describe la colonne review_scores_accuracy (23% missing):")
print("---------------------------------------")
display(df_listings["review_scores_accuracy"].unique())
display(df_listings["review_scores_accuracy"].describe())

print("\n-------------------------------------")
print("Describe la colonne review_scores_communication (23% missing):")
print("---------------------------------------")
display(df_listings["review_scores_communication"].unique())
display(df_listings["review_scores_communication"].describe())

print("\n-------------------------------------")
print("Describe la colonne review_scores_cleanliness (23% missing):")
print("---------------------------------------")
display(df_listings["review_scores_cleanliness"].unique())
display(df_listings["review_scores_cleanliness"].describe())

print("\n-------------------------------------")
print("Describe la colonne review_scores_rating (23% missing):")
print("---------------------------------------")
display(df_listings["review_scores_rating"].unique())
display(df_listings["review_scores_rating"].describe())

print("\n-------------------------------------")
print("Describe la colonne reviews_per_month (23% missing):")
print("---------------------------------------")
display(df_listings["reviews_per_month"].unique()[:10])
display(df_listings["reviews_per_month"].describe())

print("\n-------------------------------------")
print("Describe la colonne beds (0,01% missing):")
print("---------------------------------------")
display(df_listings["beds"].unique())
display(df_listings["beds"].describe())

print("\n-------------------------------------")
print("Describe la colonne bathrooms (0,01% missing):")
print("---------------------------------------")
display(df_listings["bathrooms"].unique())
display(df_listings["bathrooms"].describe())

print("\n-------------------------------------")
print("Describe la colonne bedrooms (0,01% missing):")
print("---------------------------------------")
display(df_listings["bedrooms"].unique())
display(df_listings["bedrooms"].describe())

print("\n-------------------------------------")
print("Describe la colonne host_listings_count (0,01% missing):")
print("---------------------------------------")
display(df_listings["host_listings_count"].unique()[:10])
display(df_listings["host_listings_count"].describe())

print("\n-------------------------------------")
print("Describe la colonne host_total_listings_count (0,01% missing):")
print("---------------------------------------")
display(df_listings["host_total_listings_count"].unique()[:10])
display(df_listings["host_total_listings_count"].describe())

---------------------------------------
Describe la colonne review_scores_value (23% missing):
---------------------------------------


array([nan, 10.,  9.,  8.,  6.,  7.,  2.,  4.,  5.,  3.])

count    46192.000000
mean         9.273251
std          0.888870
min          2.000000
25%          9.000000
50%          9.000000
75%         10.000000
max         10.000000
Name: review_scores_value, dtype: float64


-------------------------------------
Describe la colonne review_scores_location (23% missing):
---------------------------------------


array([nan, 10.,  9.,  8.,  6.,  4.,  7.,  5.,  2.,  3.])

count    46193.000000
mean         9.594744
std          0.716287
min          2.000000
25%          9.000000
50%         10.000000
75%         10.000000
max         10.000000
Name: review_scores_location, dtype: float64


-------------------------------------
Describe la colonne review_scores_checkin (23% missing):
---------------------------------------


array([nan, 10.,  9.,  8.,  6.,  7.,  5.,  2.,  4.,  3.])

count    46192.000000
mean         9.688236
std          0.712320
min          2.000000
25%         10.000000
50%         10.000000
75%         10.000000
max         10.000000
Name: review_scores_checkin, dtype: float64


-------------------------------------
Describe la colonne review_scores_accuracy (23% missing):
---------------------------------------


array([nan, 10.,  9.,  8.,  7.,  6.,  2.,  5.,  4.,  3.])

count    46224.000000
mean         9.574485
std          0.790243
min          2.000000
25%          9.000000
50%         10.000000
75%         10.000000
max         10.000000
Name: review_scores_accuracy, dtype: float64


-------------------------------------
Describe la colonne review_scores_communication (23% missing):
---------------------------------------


array([nan, 10.,  9.,  8.,  2.,  6.,  7.,  4.,  5.,  3.])

count    46230.000000
mean         9.719252
std          0.686441
min          2.000000
25%         10.000000
50%         10.000000
75%         10.000000
max         10.000000
Name: review_scores_communication, dtype: float64


-------------------------------------
Describe la colonne review_scores_cleanliness (23% missing):
---------------------------------------


array([nan, 10.,  9.,  8.,  6.,  7.,  4.,  2.,  5.,  3.])

count    46245.000000
mean         9.203352
std          1.062017
min          2.000000
25%          9.000000
50%          9.000000
75%         10.000000
max         10.000000
Name: review_scores_cleanliness, dtype: float64


-------------------------------------
Describe la colonne review_scores_rating (23% missing):
---------------------------------------


array([ nan, 100.,  94.,  96.,  99.,  97.,  88.,  93.,  92.,  95.,  98.,
        89.,  91.,  90.,  87.,  75.,  80.,  84.,  86.,  83.,  70.,  63.,
        78.,  85.,  81.,  82.,  20.,  76.,  72.,  71.,  73.,  40.,  60.,
        74.,  69.,  79.,  77.,  50.,  47.,  64.,  67.,  68.,  66.,  56.,
        53.,  65.,  57.,  36.,  55.,  27.,  58.,  48.,  52.])

count    46289.000000
mean        92.824494
std          8.273358
min         20.000000
25%         90.000000
50%         95.000000
75%         99.000000
max        100.000000
Name: review_scores_rating, dtype: float64


-------------------------------------
Describe la colonne reviews_per_month (23% missing):
---------------------------------------


array([ nan, 0.29, 1.29, 2.47, 0.06, 0.01, 0.24, 1.33, 1.46, 0.38])

count    47389.000000
mean         1.163733
std          1.393820
min          0.010000
25%          0.230000
50%          0.670000
75%          1.560000
max         20.930000
Name: reviews_per_month, dtype: float64


-------------------------------------
Describe la colonne beds (0,01% missing):
---------------------------------------


array([ 2.,  1.,  3.,  4.,  0.,  8.,  6.,  5., nan,  7., 10., 11.,  9.,
       16., 23., 12., 17., 20., 50., 15.])

count    59653.000000
mean         1.671634
std          1.133853
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         50.000000
Name: beds, dtype: float64


-------------------------------------
Describe la colonne bathrooms (0,01% missing):
---------------------------------------


array([ 2. ,  1. ,  nan,  1.5,  2.5,  4.5,  0.5,  0. ,  3. ,  4. ,  5. ,
        6. ,  3.5,  5.5,  6.5,  7. ,  8. ,  7.5, 50. ])

count    59805.000000
mean         1.108603
std          0.642671
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         50.000000
Name: bathrooms, dtype: float64


-------------------------------------
Describe la colonne bedrooms (0,01% missing):
---------------------------------------


array([ 2.,  1.,  0., nan,  3.,  5.,  4.,  6.,  7., 10., 50.])

count    59813.000000
mean         1.087790
std          0.974599
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         50.000000
Name: bedrooms, dtype: float64


-------------------------------------
Describe la colonne host_listings_count (0,01% missing):
---------------------------------------


array([ 2.,  1.,  3.,  6.,  4., 14.,  7., 83.,  5., 54.])

count    59873.000000
mean         8.456984
std         66.884320
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max       1305.000000
Name: host_listings_count, dtype: float64


-------------------------------------
Describe la colonne host_total_listings_count (0,01% missing):
---------------------------------------


array([ 2.,  1.,  3.,  6.,  4., 14.,  7., 83.,  5., 54.])

count    59873.000000
mean         8.456984
std         66.884320
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max       1305.000000
Name: host_total_listings_count, dtype: float64

### 2.2. Les colonnes Dtype object

In [24]:
#Vérifier les valeurs manquantes des colonnes Dtype object
print("\n-------------------------------------")
print("Les valeurs manquantes des colonnes Dtype object (sur 59881 lignes) :")
print("---------------------------------------")
missing_object_summary = pd.DataFrame({"missing_count": df_listings.select_dtypes(include="object").isna().sum(),
                                        "missing_pct": (df_listings.select_dtypes(include="object").isna().sum() / 59881 * 100).round(2)}
                                      ).sort_values("missing_pct", ascending=False)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

display(missing_object_summary)


-------------------------------------
Les valeurs manquantes des colonnes Dtype object (sur 59881 lignes) :
---------------------------------------


missing_count  missing_pct
monthly_price                             52094        87.00
weekly_price                              47739        79.72
license                                   45324        75.69
notes                                     41276        68.93
interaction                               31524        52.64
house_rules                               31406        52.45
access                                    31035        51.83
host_about                                29521        49.30
host_response_rate                        28910        48.28
host_response_time                        28910        48.28
neighborhood_overview                     24234        40.47
transit                                   21721        36.27
space                                     19365        32.34
security_deposit                          19056        31.82
cleaning_fee                              16762        27.99
first_review                              12492        20.86
last_review                               12492        20.86
host_neighbourhood                         8602        14.37
neighbourhood                              2650         4.43
summary                                    2357         3.94
zipcode                                     797         1.33
jurisdiction_names                          762         1.27
state                                       730         1.22
description                                 497         0.83
host_location                               191         0.32
market                                      132         0.22
name                                         74         0.12
city                                         21         0.04
host_picture_url                              8         0.01
host_thumbnail_url                            8         0.01
host_since                                    8         0.01
host_name                                     8         0.01
host_is_superhost                             8         0.01
host_verifications                            8         0.01
host_has_profile_pic                          8         0.01
host_identity_verified                        8         0.01
listing_url                                   0         0.00
last_scraped                                  0         0.00
street                                        0         0.00
host_url                                      0         0.00
experiences_offered                           0         0.00
picture_url                                   0         0.00
country                                       0         0.00
country_code                                  0         0.00
neighbourhood_cleansed                        0         0.00
smart_location                                0         0.00
amenities                                     0         0.00
price                                         0         0.00
room_type                                     0         0.00
bed_type                                      0         0.00
property_type                                 0         0.00
is_location_exact                             0         0.00
calendar_updated                              0         0.00
extra_people                                  0         0.00
has_availability                              0         0.00
calendar_last_scraped                         0         0.00
requires_license                              0         0.00
instant_bookable                              0         0.00
is_business_travel_ready                      0         0.00
cancellation_policy                           0         0.00
require_guest_profile_picture                 0         0.00
require_guest_phone_verification              0         0.00

In [25]:
print("\n-------------------------------------")
print("Les valeurs uniques de la colonne monthly_price (87% missing) :")
print("---------------------------------------")
display(df_listings["monthly_price"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne weekly_price (79% missing) :")
print("---------------------------------------")
display(df_listings["weekly_price"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne license (75% missing) :")
print("---------------------------------------")
display(df_listings["license"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne notes (69% missing) :")
print("---------------------------------------")
display(df_listings["notes"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne interaction (52% missing) :")
print("---------------------------------------")
display(df_listings["interaction"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne house_rules (52% missing) :")
print("---------------------------------------")
display(df_listings["house_rules"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne access (52% missing) :")
print("---------------------------------------")
display(df_listings["access"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_about (49% missing) :")
print("---------------------------------------")
display(df_listings["host_about"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_response_rate (48% missing) :")
print("---------------------------------------")
display(df_listings["host_response_rate"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_response_time (48% missing) :")
print("---------------------------------------")
display(df_listings["host_response_time"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne neighborhood_overview (40% missing) :")
print("---------------------------------------")
display(df_listings["neighborhood_overview"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne transit (36% missing) :")
print("---------------------------------------")
display(df_listings["transit"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne space (32% missing) :")
print("---------------------------------------")
display(df_listings["space"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne security_deposit (32% missing) :")
print("---------------------------------------")
display(df_listings["security_deposit"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne cleaning_fee (28% missing) :")
print("---------------------------------------")
display(df_listings["cleaning_fee"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne first_review (21% missing) :")
print("---------------------------------------")
display(df_listings["first_review"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne last_review (21% missing) :")
print("---------------------------------------")
display(df_listings["last_review"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_neighbourhood (14% missing) :")
print("---------------------------------------")
display(df_listings["host_neighbourhood"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne neighbourhood (4% missing) :")
print("---------------------------------------")
display(df_listings["neighbourhood"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne summary (3% missing) :")
print("---------------------------------------")
display(df_listings["summary"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne zipcode (1% missing) :")
print("---------------------------------------")
display(df_listings["zipcode"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne jurisdiction_names (1% missing) :")
print("---------------------------------------")
display(df_listings["jurisdiction_names"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne state (1% missing) :")
print("---------------------------------------")
display(df_listings["state"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne description (0.83% missing) :")
print("---------------------------------------")
display(df_listings["description"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_location (0.32% missing) :")
print("---------------------------------------")
display(df_listings["host_location"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne market (0.22% missing) :")
print("---------------------------------------")
display(df_listings["market"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne name (0.12% missing) :")
print("---------------------------------------")
display(df_listings["name"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne city (0.01% missing) :")
print("---------------------------------------")
display(df_listings["city"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_picture_url (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_picture_url"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_thumbnail_url (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_thumbnail_url"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_since (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_since"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_name (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_name"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_is_superhost (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_is_superhost"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_verifications (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_verifications"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_has_profile_pic (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_has_profile_pic"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_identity_verified (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_identity_verified"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne listing_url (0.01% missing) :")
print("---------------------------------------")
display(df_listings["listing_url"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne last_scraped (0.01% missing) :")
print("---------------------------------------")
display(df_listings["last_scraped"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne street (0.01% missing) :")
print("---------------------------------------")
display(df_listings["street"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne host_url (0.01% missing) :")
print("---------------------------------------")
display(df_listings["host_url"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne experiences_offered (0.01% missing) :")
print("---------------------------------------")
display(df_listings["experiences_offered"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne picture_url (0.01% missing) :")
print("---------------------------------------")
display(df_listings["picture_url"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne country (0.01% missing) :")
print("---------------------------------------")
display(df_listings["country"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne country_code (0.01% missing) :")
print("---------------------------------------")
display(df_listings["country_code"].unique()[:5])
display(df_listings["country_code"].value_counts())

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne neighbourhood_cleansed (0.01% missing) :")
print("---------------------------------------")
display(df_listings["neighbourhood_cleansed"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne smart_location (0.01% missing) :")
print("---------------------------------------")
display(df_listings["smart_location"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne is_location_exact (0% missing) :")
print("---------------------------------------")
display(df_listings["is_location_exact"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne calendar_updated (0% missing) :")
print("---------------------------------------")
display(df_listings["calendar_updated"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne extra_people (0% missing) :")
print("---------------------------------------")
display(df_listings["extra_people"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne has_availability (0% missing) :")
print("---------------------------------------")
display(df_listings["has_availability"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne calendar_last_scraped (0% missing) :")
print("---------------------------------------")
display(df_listings["calendar_last_scraped"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne requires_license (0% missing) :")
print("---------------------------------------")
display(df_listings["requires_license"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne instant_bookable (0% missing) :")
print("---------------------------------------")
display(df_listings["instant_bookable"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne is_business_travel_ready (0% missing) :")
print("---------------------------------------")
display(df_listings["is_business_travel_ready"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne cancellation_policy (0% missing) :")
print("---------------------------------------")
display(df_listings["cancellation_policy"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne require_guest_profile_picture (0% missing) :")
print("---------------------------------------")
display(df_listings["require_guest_profile_picture"].unique()[:5])

print("\n-------------------------------------")
print("Les valeurs uniques de la colonne require_guest_phone_verification (0% missing) :")
print("---------------------------------------")
display(df_listings["require_guest_phone_verification"].unique()[:5])


-------------------------------------
Les valeurs uniques de la colonne monthly_price (87% missing) :
---------------------------------------


array([None, '$2,000.00', '$2,200.00', '$1,480.00', '$1,300.00'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne weekly_price (79% missing) :
---------------------------------------


array([None, '$490.00', '$600.00', '$770.00', '$560.00'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne license (75% missing) :
---------------------------------------


array([None, '7510400829623', '5962', '7510500148022', '7511111100537044'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne notes (69% missing) :
---------------------------------------


array([None,
       'The staircase leading up to the apartment is narrow and old -- this is a very old building, so perhaps unsuitable for those with difficulty walking or climbing up stairs.',
       'Important: Be conscious that an apartment in a building of the old Paris is not an apartment in a tower of Singapore... If you do not, please do not make a request! I rent easily this place and I prefer to welcome open minded guests!',
       'Velib station outside.',
       "We participated in the very beginning of the Airbnb'adventure  in Paris in 2009 and I had the pleasure to spend a day with Joe, one of the founders, who photographed the apartment by himself. I doubt he does that again today !!! I keep a very pleasant memory of this day and I am admiring the way traveled by Airbnb with whom I hope to continue a long way."],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne interaction (52% missing) :
---------------------------------------


array([None, 'yes I can help you out',
       'We expect guests to operate rather independently, though we welcome questions about the flat and urge you to call us immediately if there is any kind of emergency or trouble.',
       'We are there to welcome you, give you keys and advice you on great places to eat & drink around.',
       "I am available 18 hours a day by text, have lots of friends (and friendly neighbors) in Paris available to help answer any questions. It's easy to rent with me. Like having your family flat for your personal use!"],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne house_rules (52% missing) :
---------------------------------------


array([None,
       'This is a small flat in a very old building that we also use when the two of us and our infant daughter come to Paris. We ask that you treat the flat as if it were your own place, and leave it reasonably tidy when you leave. No smoking or pets. Please remember to double lock the door when you step out.',
       "ELECTRICITY INCLUDED FOR NORMAL USING. PLEASE TURN OFF LIGHTS AND HEATING EACH TME YOU LEAVE IMPORTANT FOR TRASH : RESPECT THE SELECTIVE SORTING !  AND DON'T BE NOISY IN THE STAIRS WITH BAGS !",
       'Respect.',
       'This residence is limited to TWO people and is for a MINIMUM rental of SIX MONTHS.'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne access (52% missing) :
---------------------------------------


array([None,
       "The flat includes its own modern bathroom, a washing machine, stove, oven, toaster and coffee press. For sleeping there is only a fold-out couch but it has a real mattress that's rather comfortable. There is a desk that's excellent for working, bar stools, a fully-equipped kitchenette, television, closet space, wireless broadband internet, towels, linens, pots, pans, plates, forks, knives.  All you need to bring are your clothes and toothbrush. Excellent for visiting scholars, businesspersons or tourists. Absolutely no pets or smoking allowed.  ",
       'You have access to all the apartment.',
       "You are alone in the flat, the entire city is at your feet. You will enjoy being able to go outside and be astonished at the liveliness of the area and then come back home and it's facing two courtyards so there is a calm which helps make being in the center attractive.",
       'Cet appartement n est pas accessible aux Handicapés.. logement ancien et petit...'],
   


-------------------------------------
Les valeurs uniques de la colonne host_about (49% missing) :
---------------------------------------


array(["Arrivée à Casablanca il y a 4 ans, je suis amoureuse de cette ville méconnue des visiteurs hors voyage d'affaire. ",
       None,
       "We are both journalists based in the Middle East, and spend a lot of time traveling for work, so we understand what people need when they're away from home. Delphine is Parisian -- her aunt helps us rent out the apartment. We both love Paris and try to make it easy for people to come and visit the city. ",
       'I am a writer,51, author of novels, books of linguistics...',
       'Hello ! \r\nOur apartment is great and I am sure you will love it ! I will be happy to share with you tips and my favourites places to make your stay super nice.'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_response_rate (48% missing) :
---------------------------------------


array(['75%', '100%', None, '86%', '80%'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_response_time (48% missing) :
---------------------------------------


array(['within a day', 'within an hour', 'within a few hours', None,
       'a few days or more'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne neighborhood_overview (40% missing) :
---------------------------------------


array([None,
       'You are within walking distance to the Louvre, Notre Dame, Le Marais, Les Halles, Chatelet, St. Germain, Les Tuileries, le Jardin des Plantes, St. Michel, Sorbonne, Institut du Monde Arab, the Bastille and the Latin Quarter.  ',
       'This area typically Parisian, is nice, trendy and popular with, near the rue Oberkampf and its restaurants, bars, shops ... what to spend your evenings in the festive atmosphere. Also near the City Hall and the Marais district, the oldest district of Paris is also known for its "gay life". Still near the Canal Saint Martin now so characteristic of "Paris bobo" or you end up on Sunday for a picnic with friends, rollerblading or cycling ... Canal where you can also navigate a real curiosity The boulevard that stretches from the Place de la Bastille to the canal Saint Martin passing under your balcony gives oxygen and greenery with tall trees and colorful flower beds. It is also a lively area with the market very closeby (every Tuesday


-------------------------------------
Les valeurs uniques de la colonne transit (36% missing) :
---------------------------------------


array(['Metro lines : 4, 8, 3, 11, 9.', 'ligne 13 and RER B, Ligne 4',
       "The flat is close to two or three major metro lines, as well near several of Paris' Velibre stations where you can rent a bike for a small fee.",
       'Metro station HÖTEL-DE-VILLE is 100 meters close.', None],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne space (32% missing) :
---------------------------------------


array(['The district has any service or shop you may desire at a walking distance, many restaurants and clubs as well.  I will be pleased to suggest our best addresses and give you directions to have a very enjoyable journey.  We have 1 separated bedroom and one mezzanine for the second bed. One bathroom is "en suite" to the main bedroom.  Welcome to our beautiful loft! Karine',
       'I bedroom appartment in Paris 14',
       'Small, well appointed studio apartment at the very heart of Paris, on the famous Isle St Louis. FOUR-NIGHT MINIMUM.  We are looking for quiet persons or couples to rent our fully equipped and furnished studio (about 30 square meters or 300 square feet) in central Paris on the famous Isle St. Louis. Please contact us for more information. Discounts available for longer stays. The location is superb. Pick up fresh bread at the nearby boulangerie and some exquisite cheese at the local fromagerie for breakfast. Take a late night stroll along the nearby Seine. Bar h


-------------------------------------
Les valeurs uniques de la colonne security_deposit (32% missing) :
---------------------------------------


array(['$0.00', '$200.00', '$500.00', None, '$1,500.00'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne cleaning_fee (28% missing) :
---------------------------------------


array(['$40.00', '$50.00', '$36.00', '$60.00', None], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne first_review (21% missing) :
---------------------------------------


array([None, '2016-12-27', '2009-06-30', '2011-04-08', '2010-05-10'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne last_review (21% missing) :
---------------------------------------


array([None, '2018-07-27', '2018-11-21', '2018-11-19', '2015-09-14'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_neighbourhood (14% missing) :
---------------------------------------


array(['République', 'Alésia', 'Saint-Paul - Ile Saint-Louis',
       'Le Marais', "Gare du Nord - Gare de I'Est"], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne neighbourhood (4% missing) :
---------------------------------------


array(['République', 'Alésia', 'Saint-Paul - Ile Saint-Louis',
       'Le Marais', "Gare du Nord - Gare de I'Est"], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne summary (3% missing) :
---------------------------------------


array(['100 m2 loft (1100 sq feet) with high ceiling, open modern kitchen, cable tv, wifi, sleeping space up to 5 people, Republique area, 5 minutes from the St Martin Canal, Marais area, 10 min from Chatelet and the Louvre.',
       'Appartement très calme de 50M2 Belle lumière Draps et serviettes  Wifi',
       "Cozy, well-appointed and graciously designed studio apartment that mixes old and new aesthetics at the very heart of Paris, on the famous Isle St Louis that is a stone's throw from Le Marais, Quartier Latin, Notre Dame and Le Louvre. ",
       'VERY CONVENIENT, WITH THE BEST LOCATION !',
       'Very large & nice apartment all for you!  - Sunny living room & bedrooms - Well equiped and furnished - Central location & walking distance to many attractions - Great neighborhood'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne zipcode (1% missing) :
---------------------------------------


array(['75010', '75014', '75004', '75009', '75020'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne jurisdiction_names (1% missing) :
---------------------------------------


array(['{PARIS}', None, '{Paris}', '{"LEVALLOIS PERRET"}', '{VINCENNES}'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne state (1% missing) :
---------------------------------------


array(['Île-de-France', 'Ile-de-France', 'IDF', None, 'IdF'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne description (0.83% missing) :
---------------------------------------


array(['100 m2 loft (1100 sq feet) with high ceiling, open modern kitchen, cable tv, wifi, sleeping space up to 5 people, Republique area, 5 minutes from the St Martin Canal, Marais area, 10 min from Chatelet and the Louvre. The district has any service or shop you may desire at a walking distance, many restaurants and clubs as well.  I will be pleased to suggest our best addresses and give you directions to have a very enjoyable journey.  We have 1 separated bedroom and one mezzanine for the second bed. One bathroom is "en suite" to the main bedroom.  Welcome to our beautiful loft! Karine Metro lines : 4, 8, 3, 11, 9.',
       'I bedroom appartment in Paris 14',
       "Cozy, well-appointed and graciously designed studio apartment that mixes old and new aesthetics at the very heart of Paris, on the famous Isle St Louis that is a stone's throw from Le Marais, Quartier Latin, Notre Dame and Le Louvre. Small, well appointed studio apartment at the very heart of Paris, on the famous Isle 


-------------------------------------
Les valeurs uniques de la colonne host_location (0.32% missing) :
---------------------------------------


array(['Casablanca, Grand Casablanca, Morocco',
       'Paris, Île-de-France, France', 'Istanbul, İstanbul, Turkey',
       'Paris, Ile-de-France, France',
       'New York, New York, United States'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne market (0.22% missing) :
---------------------------------------


array(['Paris', 'Other (International)', 'Loire Valley', 'Toulouse',
       'Orleans'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne name (0.12% missing) :
---------------------------------------


array(['Loft for 4 by Canal Saint Martin', 'zen and calm',
       'Explore the heart of old Paris',
       'MARAIS - 2ROOMS APT - 2/4 PEOPLE',
       'Large & sunny flat with balcony !'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne city (0.01% missing) :
---------------------------------------


array(['Paris', 'Paris, 4th arrondissement', 'Saint-Mandé', 'Paris ',
       'Paris-13E-Arrondissement'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_picture_url (0.01% missing) :
---------------------------------------


array(['https://a0.muscache.com/im/pictures/17fe6c88-a480-4a63-bfa7-1c0951105958.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/3631/profile_pic/1375800198/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/7903/profile_pic/1280002723/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/pictures/58f00c4d-f805-4605-9f7c-5c848814c828.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/22155/profile_pic/1271497205/original.jpg?aki_policy=profile_x_medium'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_thumbnail_url (0.01% missing) :
---------------------------------------


array(['https://a0.muscache.com/im/pictures/17fe6c88-a480-4a63-bfa7-1c0951105958.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/3631/profile_pic/1375800198/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/7903/profile_pic/1280002723/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/pictures/58f00c4d-f805-4605-9f7c-5c848814c828.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/22155/profile_pic/1271497205/original.jpg?aki_policy=profile_small'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_since (0.01% missing) :
---------------------------------------


array(['2008-09-09', '2008-10-14', '2009-02-14', '2008-08-30',
       '2009-06-18'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_name (0.01% missing) :
---------------------------------------


array(['Karine', 'Anne', 'Borzou', 'Franck', 'Anaïs'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_is_superhost (0.01% missing) :
---------------------------------------


array(['f', 't', None], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_verifications (0.01% missing) :
---------------------------------------


array(["['email', 'phone', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'facebook', 'reviews']",
       "['email', 'phone', 'facebook', 'google', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']",
       "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'government_id']"],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_has_profile_pic (0.01% missing) :
---------------------------------------


array(['t', 'f', None], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_identity_verified (0.01% missing) :
---------------------------------------


array(['t', 'f', None], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne listing_url (0.01% missing) :
---------------------------------------


array(['https://www.airbnb.com/rooms/2577',
       'https://www.airbnb.com/rooms/3109',
       'https://www.airbnb.com/rooms/5396',
       'https://www.airbnb.com/rooms/7397',
       'https://www.airbnb.com/rooms/7964'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne last_scraped (0.01% missing) :
---------------------------------------


array(['2018-12-08', '2018-12-07'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne street (0.01% missing) :
---------------------------------------


array(['Paris, Île-de-France, France', 'Paris, Ile-de-France, France',
       'Paris, IDF, France', 'Paris, France', 'Paris, IdF, France'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne host_url (0.01% missing) :
---------------------------------------


array(['https://www.airbnb.com/users/show/2827',
       'https://www.airbnb.com/users/show/3631',
       'https://www.airbnb.com/users/show/7903',
       'https://www.airbnb.com/users/show/2626',
       'https://www.airbnb.com/users/show/22155'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne experiences_offered (0.01% missing) :
---------------------------------------


array(['none'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne picture_url (0.01% missing) :
---------------------------------------


array(['https://a0.muscache.com/im/pictures/09da057c-0120-4d5c-b464-d95c75921dde.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/baeae9e2-cd53-4ac3-b1bc-4055c0bb2e77.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/52413/f9bf76f5_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/67928287/330bd78c_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/4471349/6fb3de47_original.jpg?aki_policy=large'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne country (0.01% missing) :
---------------------------------------


array(['France', 'Switzerland'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne country_code (0.01% missing) :
---------------------------------------


array(['FR', 'CH'], dtype=object)

country_code
FR    59880
CH        1
Name: count, dtype: int64


-------------------------------------
Les valeurs uniques de la colonne neighbourhood_cleansed (0.01% missing) :
---------------------------------------


array(['Entrepôt', 'Observatoire', 'Hôtel-de-Ville', 'Opéra',
       'Ménilmontant'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne smart_location (0.01% missing) :
---------------------------------------


array(['Paris, France', 'Paris, 4th arrondissement, France',
       'Saint-Mandé, France', 'Paris , France',
       'Paris-13E-Arrondissement, France'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne is_location_exact (0% missing) :
---------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne calendar_updated (0% missing) :
---------------------------------------


array(['4 weeks ago', '5 days ago', '6 days ago', 'today', '2 days ago'],
      dtype=object)


-------------------------------------
Les valeurs uniques de la colonne extra_people (0% missing) :
---------------------------------------


array(['$0.00', '$10.00', '$45.00', '$30.00', '$4.00'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne has_availability (0% missing) :
---------------------------------------


array(['t'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne calendar_last_scraped (0% missing) :
---------------------------------------


array(['2018-12-08', '2018-12-07'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne requires_license (0% missing) :
---------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne instant_bookable (0% missing) :
---------------------------------------


array(['t', 'f'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne is_business_travel_ready (0% missing) :
---------------------------------------


array(['f'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne cancellation_policy (0% missing) :
---------------------------------------


array(['strict_14_with_grace_period', 'flexible', 'moderate',
       'super_strict_30', 'strict'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne require_guest_profile_picture (0% missing) :
---------------------------------------


array(['f', 't'], dtype=object)


-------------------------------------
Les valeurs uniques de la colonne require_guest_phone_verification (0% missing) :
---------------------------------------


array(['f', 't'], dtype=object)

### 2.2. Les colonnes Dtype int

In [26]:
#Vérifier les valeurs manquantes des colonnes Dtype int
print("\n-------------------------------------")
print("Les valeurs manquantes des colonnes Dtype int (sur 59881 lignes) :")
print("---------------------------------------")
missing_int_summary = pd.DataFrame({"missing_count": df_listings.select_dtypes(include="int").isna().sum(),
                                        "missing_pct": (df_listings.select_dtypes(include="int").isna().sum() / 59881 * 100).round(2)}
                                      ).sort_values("missing_pct", ascending=False)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

display(missing_int_summary)


-------------------------------------
Les valeurs manquantes des colonnes Dtype int (sur 59881 lignes) :
---------------------------------------


missing_count  missing_pct
id                                          0          0.0
scrape_id                                   0          0.0
host_id                                     0          0.0
accommodates                                0          0.0
guests_included                             0          0.0
minimum_nights                              0          0.0
maximum_nights                              0          0.0
availability_30                             0          0.0
availability_60                             0          0.0
availability_90                             0          0.0
availability_365                            0          0.0
number_of_reviews                           0          0.0
calculated_host_listings_count              0          0.0

In [27]:
print("\n-------------------------------------")
print("Describe la colonne accommodates (0% missing):")
print("---------------------------------------")
display(df_listings["accommodates"].unique()[:5])
display(df_listings["accommodates"].describe())

print("\n-------------------------------------")
print("Describe la colonne guests_included (0% missing):")
print("---------------------------------------")
display(df_listings["guests_included"].unique()[:5])
display(df_listings["guests_included"].describe())

print("\n-------------------------------------")
print("Describe la colonne minimum_nights (0% missing):")
print("---------------------------------------")
display(df_listings["minimum_nights"].unique()[:5])
display(df_listings["minimum_nights"].describe())

print("\n-------------------------------------")
print("Describe la colonne maximum_nights (0% missing):")
print("---------------------------------------")
display(df_listings["maximum_nights"].unique()[:5])
display(df_listings["maximum_nights"].describe())

print("\n-------------------------------------")
print("Describe la colonne availability_30 (0% missing):")
print("---------------------------------------")
display(df_listings["availability_30"].unique()[:5])
display(df_listings["availability_30"].describe())

print("\n-------------------------------------")
print("Describe la colonne availability_60 (0% missing):")
print("---------------------------------------")
display(df_listings["availability_60"].unique()[:5])
display(df_listings["availability_60"].describe())

print("\n-------------------------------------")
print("Describe la colonne availability_90 (0% missing):")
print("---------------------------------------")
display(df_listings["availability_90"].unique()[:5])
display(df_listings["availability_90"].describe())

print("\n-------------------------------------")
print("Describe la colonne availability_365 (0% missing):")
print("---------------------------------------")
display(df_listings["availability_365"].unique()[:5])
display(df_listings["availability_365"].describe())

print("\n-------------------------------------")
print("Describe la colonne number_of_reviews (0% missing):")
print("---------------------------------------")
display(df_listings["number_of_reviews"].unique()[:5])
display(df_listings["number_of_reviews"].describe())

print("\n-------------------------------------")
print("Describe la colonne calculated_host_listings_count (0% missing):")
print("---------------------------------------")
display(df_listings["calculated_host_listings_count"].unique()[:5])
display(df_listings["calculated_host_listings_count"].describe())


-------------------------------------
Describe la colonne accommodates (0% missing):
---------------------------------------


array([4, 2, 3, 5, 6])

count    59881.000000
mean         3.041148
std          1.531710
min          1.000000
25%          2.000000
50%          2.000000
75%          4.000000
max         17.000000
Name: accommodates, dtype: float64


-------------------------------------
Describe la colonne guests_included (0% missing):
---------------------------------------


array([1, 2, 3, 4, 5])

count    59881.000000
mean         1.445200
std          0.971009
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         16.000000
Name: guests_included, dtype: float64


-------------------------------------
Describe la colonne minimum_nights (0% missing):
---------------------------------------


array([  3,   2,  10, 180,   5])

count    59881.000000
mean         5.411366
std         50.211773
min          1.000000
25%          2.000000
50%          2.000000
75%          4.000000
max       9999.000000
Name: minimum_nights, dtype: float64


-------------------------------------
Describe la colonne maximum_nights (0% missing):
---------------------------------------


array([1125,   15,   30,   23,  365])

count    5.988100e+04
mean     8.768937e+02
std      4.104180e+04
min      1.000000e+00
25%      3.000000e+01
50%      1.125000e+03
75%      1.125000e+03
max      1.000000e+07
Name: maximum_nights, dtype: float64


-------------------------------------
Describe la colonne availability_30 (0% missing):
---------------------------------------


array([12,  3,  1,  4,  0])

count    59881.000000
mean         4.359797
std          7.374459
min          0.000000
25%          0.000000
50%          0.000000
75%          6.000000
max         30.000000
Name: availability_30, dtype: float64


-------------------------------------
Describe la colonne availability_60 (0% missing):
---------------------------------------


array([13,  4,  6, 33, 30])

count    59881.000000
mean        10.974583
std         16.988522
min          0.000000
25%          0.000000
50%          0.000000
75%         17.000000
max         60.000000
Name: availability_60, dtype: float64


-------------------------------------
Describe la colonne availability_90 (0% missing):
---------------------------------------


array([13, 17, 28, 49,  4])

count    59881.000000
mean        19.231192
std         27.942993
min          0.000000
25%          0.000000
50%          1.000000
75%         35.000000
max         90.000000
Name: availability_90, dtype: float64


-------------------------------------
Describe la colonne availability_365 (0% missing):
---------------------------------------


array([ 39, 271, 113, 286, 164])

count    59881.000000
mean        85.390324
std        122.934236
min          0.000000
25%          0.000000
50%          6.000000
75%        156.000000
max        365.000000
Name: availability_365, dtype: float64


-------------------------------------
Describe la colonne number_of_reviews (0% missing):
---------------------------------------


array([  0,   7, 148, 231,   6])

count    59881.000000
mean        18.426045
std         36.820801
min          0.000000
25%          1.000000
50%          6.000000
75%         19.000000
max        744.000000
Name: number_of_reviews, dtype: float64


-------------------------------------
Describe la colonne calculated_host_listings_count (0% missing):
---------------------------------------


array([1, 6, 3, 2, 4])

count    59881.000000
mean         4.352983
std         16.179109
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        173.000000
Name: calculated_host_listings_count, dtype: float64

# 3. Les colonnes à prendre ou à laisser

### Les colonnes à garder absolument et transformer en cas de besoin :

- Identité & localisation (cartographie, clustering, matching géospatial, itinéraires) : latitude (0% missing), longitude (0% missing), name (0,1% missing), city (0,1% missing), zipcode (1% missing), transit (36% missing), listing_url (0.01% missing)

- Type de logement & capacité : description (1% missing), property_type (0% missing), bedrooms (0.11% missing), beds (% missing), bed_type (0% missing), bathrooms (0.13% missing), accommodates (ex : accommodates=2 --> logement pour 2 personnes) (0% missing), amenities (0% missing)

- Prix : price (0% missing), cleaning_fee (27% missing), guests_included (0% missing), extra_people (0% missing)

- Règles : security_deposit (31% missing), minimum_nights (0% missing), maximum_nights (0% missing), cancellation_policy (0% missing), require_guest_profile_picture (0% missing), require_guest_phone_verification (0% missing), 

- Disponibilité : availability_30 (ex : availability_30 = 12 → 12 nuits libres sur les 30 à venir) (0% missing), availability_60 (0% missing), availability_90 (0% missing), availability_365 (0% missing)

- Avis & réputation (score) : number_of_reviews (0% missing), review_scores_rating (23% missing), reviews_per_month (21% missing), last_review (21% missing), review_scores_location (23% missing), review_scores_cleanliness (23% missing), review_scores_value (23% missing),

### Les colonnes à ignorer :

neighborhood_overview (40% missing), space (32% missing), notes (69% missing), interaction (52% missing), summary (4% missing), house_rules (52% missing), access (52% missing), host_url (0% missing), host_name (0,01% missing), host_identity_verified (0,01% missing), host_about (49% missing), host_since (0,01% missing), host_is_superhost (0,01% missing), room_type (0% missing),host_response_time (48% missing), 

host_verifications (0,01% missing), host_response_rate (48% missing), first_review (21% missing), review_scores_checkin (23% missing), review_scores_accuracy (23% missing), review_scores_communication (23% missing), calendar_updated (0% missing), has_availability (0% missing), is_location_exact (0% missing), street (0% missing), country (0% missing), country_code (0% missing), neighbourhood_cleansed (0% missing), host_id (0% missing), host_listings_count (0.01% missing), host_total_listings_count (0.01% missing), picture_url (0% missing), smart_location (0% missing), requires_license (0% missing), calculated_host_listings_count (0% missing), scrape_id (0% missing), thumbnail_url (100% missing), medium_url (100% missing), xl_picture_url (100% missing), host_acceptance_rate (100% missing), instant_bookable (0% missing), neighbourhood_group_cleansed (100% missing), host_thumbnail_url (0,01% missing), host_picture_url (0,01% missing), jurisdiction_names (1% missing), experiences_offered (0% missing), , square_feet (98% missing), host_neighbourhood (14% missing), state (1% missing), host_location (0,3% missing), market (0,2% missing), host_has_profile_pic (0,01% missing), is_business_travel_ready (0% missing), has_availability (0% missing), last_scraped (0% missing)

# 4. Nettoyer + compléter + transformer les valeurs

In [4]:
#transformer en booléen les colonnes require_guest_phone_verification (0% missing), require_guest_profile_picture (0% missing), 
''''
BOOL_COLS = ["require_guest_phone_verification", "require_guest_profile_picture", "host_is_superhost", "host_identity_verified"]
for col in BOOL_COLS:
    if col in df_listings.columns:
        df_listings[col] = (df_listings[col].astype(str).str.lower().isin(["t", "true", "1", "yes"]))
''''

In [5]:
#transformer en Dates : last_review (21% missing), first_review (21% missing), host_since (0,01% missing)
''''
DATE_COLS = ["last_review", "first_review", "host_since"]
for col in DATE_COLS:
    if col in df_listings.columns:
        df_listings[col] = pd.to_datetime(df_listings[col], errors="coerce")
''''

In [32]:
#transformer en colonnes catégorielles (optimisation mémoire) : room_type (% missing), property_type (% missing),
# bed_type (0% missing), neighbourhood_cleansed (% missing), cancellation_policy (0% missing)
''''
CAT_COLS = ["room_type", "property_type", "bed_type", "cancellation_policy"]
for col in CAT_COLS:
    if col in df_listings.columns:
        df_listings[col] = df_listings[col].astype("category")
''''

In [33]:
#transformer en liste : amenities (0% missing)
'''
df_listings["amenities_list"] = (df_listings["amenities"].astype(str).str.strip("{}").str.replace('"', "").str.split(","))
'''

In [4]:
#transformer en capacités types numériques propres : accommodates (0% missing), bedrooms (0.11% missing), beds (% missing),
#bathrooms (0.13% missing), minimum_nights (0% missing), maximum_nights (0% missing), guests_included (0% missing)

INT_COLS = ["accommodates", "bedrooms", "beds", "bathrooms", "minimum_nights", "maximum_nights", "guests_included"]
for col in INT_COLS:
    if col in df_listings.columns:
        df_listings[col] = pd.to_numeric(df_listings[col], errors="coerce")

In [5]:
#convertir review_scores_rating sur 5
df_listings["review_scores_rating"] = (pd.to_numeric(df_listings["review_scores_rating"], errors="coerce") / 20).round(2)

In [6]:
#Nettoyer + transformer en float : price (0% missing), cleaning_fee (27% missing), security_deposit (31% missing),
#extra_people (0% missing), weekly_price (79% missing), monthly_price (87% missing)

PRICE_COLS = ["price", "cleaning_fee", "security_deposit", "extra_people", "weekly_price", "monthly_price"]
for col in PRICE_COLS:
    if col in df_listings.columns:
        df_listings[col] = (df_listings[col].astype(str).str.replace(r"[^0-9.]", "", regex=True))
        df_listings[col] = pd.to_numeric(df_listings[col], errors="coerce")
        df_listings[col] = df_listings[col].astype("float").fillna(0)

In [7]:
#créer et calculer la colonne "price_level" en mode quantiles basant sur colonne "price" : 1=petit <= q1 ; q1 < 2=moyen <= q2 ; 3=confort > q2

#regarder la distribution
df_listings["price"].describe(percentiles=[0.33, 0.66])

#calculer les seuils
q1 = df_listings["price"].quantile(0.33)
q2 = df_listings["price"].quantile(0.66)
q1, q2

#créer price_level
df_listings["price_level"] = np.nan

df_listings.loc[df_listings["price"] <= q1, "price_level"] = 1
df_listings.loc[(df_listings["price"] > q1) & (df_listings["price"] <= q2), "price_level"] = 2
df_listings.loc[df_listings["price"] > q2, "price_level"] = 3

df_listings[["price_level", "price"]].head(5)

price_level  price
0          3.0  125.0
1          2.0   75.0
2          3.0  115.0
3          3.0  115.0
4          2.0   99.0

# 5. DataFrame Final (normer les colonnes afin de mapper avec les autres datasets dans streamlit)

19 colonnes normées UX streamlit : source_id, source, type, raw_type, url, lat, lon, name, address, postal_code, city, region, country, snippet, rating, review_count, price_level, max_people, distance_km

In [8]:
# Alléger le df --> Filtre qualité (garder seulement avec rating + min avis)
#df_listings = df_listings[df_listings["review_scores_rating"].notna() & (df_listings["number_of_reviews"] >= 3)]

# Alléger le df --> tronquer la colonne "description"
#df_listings["description_tron"] = (df_listings["description"].fillna("").astype(str).str.replace(r"\s+", " ", regex=True).str.strip().str.slice(0, 350))

# Garder uniquement les colonnes utiles
cols_keep = ["id", "listing_url", "name", "city", "zipcode", "state", "country",
             "latitude", "longitude", "review_scores_rating", "number_of_reviews", "accommodates", "price", "price_level"]

df_airbnb_clean = df_listings[cols_keep].copy()

# Créer les colonnes standards et les colonnes manquantes pour UX design
df_airbnb_clean["source"] = "AirBnb-Paris"
df_airbnb_clean["type"] = "Airbnb"
df_airbnb_clean["raw_type"] = np.nan
df_airbnb_clean["distance_km"] = np.nan
df_airbnb_clean["address"] = np.nan
df_airbnb_clean["snippet"] = np.nan

# Normaliser / renommer
rename_map={"id": "source_id",
            "listing_url": "url",
            "latitude": "lat",
            "longitude": "lon",
            "zipcode": "postal_code",
            "state": "region",
            "review_scores_rating": "rating",
            "number_of_reviews": "review_count",
            "accommodates": "max_people"}
df_airbnb_clean_norm = df_airbnb_clean.rename(columns = rename_map, errors="ignore")

# réordonner les colonnes UX
UX_COLUMNS = ["source_id", "source", "type", "raw_type", "url", "lat", "lon",
              "name", "address", "postal_code", "city", "region", "country",
              "snippet", "rating", "review_count", "price_level", "max_people", "distance_km", "price"]

for col in UX_COLUMNS:
    if col not in df_airbnb_clean_norm.columns:
        df_airbnb_clean_norm[col] = None
        
df_airbnb_clean_normux = df_airbnb_clean_norm[UX_COLUMNS]

#sauvegarder les changements
df_airbnb_clean_normux_fast = df_airbnb_clean_normux.copy()

# Export parquet final (un seul fichier)
df_airbnb_clean_normux_fast.to_parquet("df_airbnb_clean_normux_fast.parquet", index=False, engine="pyarrow", compression="zstd", compression_level=9)

#vérifier
display(df_airbnb_clean_normux_fast.head(3))
display(df_airbnb_clean_normux_fast.info())

#Exporter en CSV
#output_path = "df_trip_idf_clean_final.csv"
#df_trip_idf_clean_final.to_csv(output_path, index = False, encoding="utf-8-sig")

source_id        source    type  raw_type  \
0       2577  AirBnb-Paris  Airbnb       NaN   
1       3109  AirBnb-Paris  Airbnb       NaN   
2       5396  AirBnb-Paris  Airbnb       NaN   

                                 url        lat       lon  \
0  https://www.airbnb.com/rooms/2577  48.869933  2.362511   
1  https://www.airbnb.com/rooms/3109  48.833494  2.318518   
2  https://www.airbnb.com/rooms/5396  48.851001  2.358690   

                               name  address postal_code   city  \
0  Loft for 4 by Canal Saint Martin      NaN       75010  Paris   
1                      zen and calm      NaN       75014  Paris   
2    Explore the heart of old Paris      NaN       75004  Paris   

          region country  snippet  rating  review_count  price_level  \
0  Île-de-France  France      NaN     NaN             0          3.0   
1  Île-de-France  France      NaN     5.0             7          2.0   
2  Ile-de-France  France      NaN     4.7           148          3.0   

   max_people  distance_km  price  
0           4          NaN  125.0  
1           2          NaN   75.0  
2           2          NaN  115.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59881 entries, 0 to 59880
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   source_id     59881 non-null  int64  
 1   source        59881 non-null  object 
 2   type          59881 non-null  object 
 3   raw_type      0 non-null      float64
 4   url           59881 non-null  object 
 5   lat           59881 non-null  float64
 6   lon           59881 non-null  float64
 7   name          59807 non-null  object 
 8   address       0 non-null      float64
 9   postal_code   59084 non-null  object 
 10  city          59860 non-null  object 
 11  region        59151 non-null  object 
 12  country       59881 non-null  object 
 13  snippet       0 non-null      float64
 14  rating        46289 non-null  float64
 15  review_count  59881 non-null  int64  
 16  price_level   59881 non-null  float64
 17  max_people    59881 non-null  int64  
 18  distance_km   0 non-null  

None

# 6. Carte de points avec clustering

In [23]:
#Créer la carte
#m = folium.Map(location=[48.85, 2.35], zoom_start=9, tiles="OpenStreetMap")

#Ajouter le clustering
#marker_cluster = MarkerCluster().add_to(m)

#Ajouter les POI
#for _, row in df_listings_clean_final.iterrows():
#    folium.Marker(location=[row["latitude"], row["longitude"]], popup=f"""<b>{row["price"]}<b><br><br><i>{row["property_type"]}<i></br></br>{row["listing_url"]}""").add_to(marker_cluster)

#m.save("map_airbnb_idf.html")
#m